### PR TITLE
Update dependencies

### LINKED ISSUE #106: Update dependencies
This may break compatibility with older versions of node, but may correct bugs we don't know about.

### PR DESCRIPTION
**Pull request by eladnava**
```
 lodash      ^3.10.1  →  ^4.17.10 
 request      2.81.0  →    2.85.0 
 mocha        ^2.2.4  →    ^5.1.1 
 proxyquire   ^1.4.0  →    ^2.0.1 
 sinon       ^1.14.1  →    ^5.0.7 
```

Only one `devDependency` has not been updated, `chai`, as updating it breaks about 25 tests. Minimum Node version 4.0 mentioned in README. Version bumped to `1.0.0`. 

`npm audit` returns:

```
[+] no known vulnerabilities found [130 packages audited]
```

Closes #106.

@hypesystem Looks good?

### CODE REVIEW

**Comment by hypesystem** [comment]
Great :smile: we should probably work on getting chai updated, too, at some point.

Will you `npm publish`?

**Comment by jkowalleck** [comment]
Looks like `engines` was not updated in `package.json`.
I am on mobile, maybe I am just not having the right view.

**Comment by hypesystem** [comment]
You are right, @jkowalleck !

@eladnava will you update the  `engines` part before publishing?

**Comment by jkowalleck** [comment]
Thank you for your work, @eladnava and @hypesystem

**Comment by eladnava** [comment]
@jkowalleck Thank you! 👍

**Comment by eladnava** [comment]
@jkowalleck Thank you! 👍 

Published `1.0.0` to npm.

**Comment by hypesystem** [comment]
Better late than never :smile: integers are cheap :fireworks:

**Pull request merged**
