### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nonemoticoner**
I propose such solution for #70 No need to make it more complex. Let's keep it simple.

### CODE REVIEW

**Comment by hypesystem** [comment]
Great! Thanks for the PR. I have a few notes:

- If you are only adding a single data field, the *shorter* syntax would be `message.addData("key1", "msg1");`
- I would prefer to show off the `Sender#send` method, rather than `Sender#sendNoRetry`. All you need to do is change the method name -- it takes the same arguments.
- I really do think the section should appear *before* usage. It seems the primary source for confusion is stumbling upon code, trying to run it, and seeing it not work. Let's make it easy to try to run something.

**Comment by hypesystem** [comment]
Uh, and one small thing: we should try and be consistent with the code style. The other examples use this for error logging:

```js
if(err) console.error(err);
else    console.log(result);
```

You should probably use this to be consistent :)

**Comment by Nonemoticoner** [comment]
Done, as you pleased. I'm not that convinced to be so consistent. For me, it implies too much Ctrl+C > Ctrl+V bad practice but whatever. I believe you can merge it now.

**Comment by hypesystem** [comment]
Great! Remember to add yourself to the contributors list in package.json and in the README - then I'll merge :)

**Comment by Nonemoticoner** [comment]
Done, you can merge ;)

**Comment by hypesystem** [comment]
Sorry for the long wait - I got hit by the flu :(

**Pull request merged**
