### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by ashrko619**
#124 opened by AdamBrodzinski

### CODE REVIEW

**Comment by hypesystem** [comment]
Great, thank you! Remember to add yourself to the contributors -- otherwise I am ready to merge.

**Comment by ashrko619** [comment]
Done updating the Contributing Section

**Comment by hypesystem** [comment]
I should have been more precise. There is also the contributors section in the package.json, which will make you show up on npmjs.org: https://github.com/ToothlessGear/node-gcm/blob/master/package.json#L6-L32

**Comment by ashrko619** [comment]
Did not know about that . I have updated it now, thank you !

**Pull request merged**
