### PR TITLE
Support explicit topic target in send()

### PR DESCRIPTION
**Pull request by bastienleonard**
Following issue #146:

This is a quick fix for sending to a topic with `send()`:

```javascript
sender.send(
    message,
    { topic: '/topics/global' }, // can also be { registrationIds: [...] },
    { retries: 2 },
    callback
);
```

If it looks good enough, I'll add support for the same parameters for `sendNoRetry()`.

### CODE REVIEW

**Comment by hypesystem** [comment]
Seeing as you are changing the possible contents of the second parameter of send, I think it would be fitting to rename it `registrationIds -> recipient` (likewise, `originalRegIds -> originalRecipient`). This makes clearer what the variable contains.

It looks good, and it would be nice to support this in `sendNoRetry`.

Remember to add tests for sending to topics and add yourself to the contributors in package.json.

**Comment by bastienleonard** [comment]
* Make the same change in `sendNoRetry()`

**Comment by bastienleonard** [comment]
* Rename `registrationIds` to `recipient`

**Comment by bastienleonard** [comment]
* Return an error if an object with no keys or invalid keys is passed
* Add unit tests

**Comment by bastienleonard** [comment]
That's all for today. I just realized that I should probably add support for `notificationKey`.

**Comment by hypesystem** [comment]
Looks really good! I had a few comments. Other than that I see the following things missing:

- `notificationKey` support (as you suggest)
- Update README
- Add yourself to contributors in package.json

Thank you so much for your time :)

**Comment by bastienleonard** [comment]
* Support `recipient.notificationKey`

**Comment by bastienleonard** [comment]
* Remove duplication of recipient extraction
* Explicit errors when recipient keys are invalid

**Comment by bastienleonard** [comment]
* Remove duplication of recipient extraction
* Explicit errors when recipient keys are invalid

**Comment by bastienleonard** [comment]
* Remove duplication of recipient extraction
* Explicit errors when recipient keys are invalid

**Comment by bastienleonard** [comment]
(Will update the readme and contributors list after work, if you're OK with the changes)

**Comment by hypesystem** [comment]
Looks good :) Let me know when you've updated README and contributors, and I will merge :)

**Comment by bastienleonard** [comment]
* Update the readme. I decided to use an explicit recipient everywhere (e.g. `{ registrationIds: [...] }`), not sure what's your take on this.
* Update contributors in package.json

**Comment by hypesystem** [comment]
Looks good :) I think the explicit recipient-type is the best model until we make a breaking change, so we should encourage that in the README.

**Comment by hypesystem** [comment]
Just now released in 0.12.0

**Pull request merged**
