### PR TITLE
Allow uri override

### LINKED ISSUE #344: Make send URI configurable
Send URI is hard-coded in `Constants.GCM_SEND_URI`.  
Ability to set custom uri via Sender options may help with integration testing (using mock GCM endpoint).

### PR DESCRIPTION
**Pull request by pertu**
Closes #344

### CODE REVIEW

**Comment by hypesystem** [comment]
Looks good! Feel free to add yourself to contributors in package.json too :smile:

**Comment by pertu** [comment]
> Feel free to add yourself to contributors
Thanks for suggestion, maybe next time :)

**Comment by eladnava** [comment]
@hypesystem @pertu LTGM! Feel free to merge and publish :smile:

**Comment by pertu** [comment]
> @hypesystem @pertu LTGM! Feel free to merge and publish :smile:

I don't have write access to this repository.
Could you please help me with merge?

**Comment by eladnava** [comment]
@pertu Sure thing, the request was meant for @hypesystem but nevermind :) 

I've published to npm as `1.0.3`. Thanks again! 🎉

**Pull request merged**
