### PR TITLE
Support for multiple topics using condition parameter of FCM send API

### PR DESCRIPTION
**Pull request by vibgy**
Aimed to solve this issue: https://github.com/ToothlessGear/node-gcm/issues/261

### CODE REVIEW

**Comment by hypesystem** [comment]
I think this looks pretty good :-)

You don't need to do the version bump, we will do that when we publish the update :-)

Would like to hear final thoughts from @eladnava

**Comment by eladnava** [comment]
@vibgy @hypesystem looks good! Feel free to merge. 😄

**Comment by vibgy** [comment]
Should I remove the version change?

**Comment by vibgy** [comment]
@eladnava @hypesystem - I dont have permissions to merge. Also, should I remove the version change?

**Comment by eladnava** [comment]
@vibgy Yes, please 👍

**Comment by vibgy** [comment]
@eladnava - Reverted the version number change in package.json.. All tests still pass. Its ready to be merged.

**Comment by eladnava** [comment]
@vibgy Thanks so much for your contribution! Excellent job. 😄 
@hypesystem can I increment version and publish to npm?

**Comment by hypesystem** [comment]
@vibgy thanks for your effort on this :-)

@eladnava yeah! Remember to ensure that the CHANGELOG has all changes :)

**Comment by eladnava** [comment]
@hypesystem Changelog looks good. Published 0.14.4. 😄

**Comment by hypesystem** [comment]
:shipit: :star:

**Comment by djvickx** [comment]
@vibgy it only supports upto 5 topics using condition. How I can send to around 10 topics?

**Comment by hypesystem** [comment]
Hey @djvickx if would be great if you could create a new issue for your problem. If you include the code where you attempt to send to 10 topics and explain the problem you encounter that would give us a good starting point for investigating and helping you :smile:

**Comment by djvickx** [comment]
> 
> 
> Hey @djvickx if would be great if you could create a new issue for your problem. If you include the code where you attempt to send to 10 topics and explain the problem you encounter that would give us a good starting point for investigating and helping you 😄

```
condition = "'TopicA' in topics || 'TopicB' in topics || 'TopicC' in topics || 'TopicD' in topics || 'TopicE' in topics || 'TopicF' in topics || 'TopicG' in topics "
            string serverKey = //SERVER_KEY

                WebRequest tRequest = WebRequest.Create("https://fcm.googleapis.com/fcm/send");
                tRequest.Method = "post";
                tRequest.ContentType = "application/json";
                var objNotification = new
                {
                    condition = condition,
                    priority = "high",
                    data = notifyData
                };

                WebResponse tResponse = tRequest.GetResponse();
```

As per firebase documentation, they don't allow more than 5 topics when using **condition**.

**Comment by hypesystem** [comment]
Hey @djvickx ! It would be much cleaner for us to deal with your issue if you create a separate ticket.

Click here: https://github.com/ToothlessGear/node-gcm/issues/new

Then fill in your question there, and we can take the discussion there.

Discussion here (on this Pull Request) should regard the Pull Request. Your question regards how to send to multiple topics, and is not really related to the code here. That's why I'm asking you to create a new issue :smile: I hope this makes sense!

**Pull request merged**
