### PR TITLE
Fix issue when using module behind a proxy

### PR DESCRIPTION
**Pull request by pablonazareno**
Add flag for old proxy usage when making request to google GCM with request module.
Fix issue #97

### CODE REVIEW

**Comment by hypesystem** [comment]
Nice -- very simple fix!

Would it be possible to write a test that fails with the old code but passes after this fix?

**Comment by pablonazareno** [comment]
Other solution is use version 2.40.0 of request module at package.json
This version is previous to proxy changes.

**Comment by hypesystem** [comment]
I prefer the solution where we can use the latest version of request.

I find it very interesting that they introduced breaking changes in a minor version bump.

The commit that broke it on our side is this one: https://github.com/ToothlessGear/node-gcm/commit/ad651d5a54f200c558120b4d1a163a6287b4d5af

I would still like to see some kind of test of this functionality, proving what is fixed :)

**Comment by eladnava** [comment]
Closed due to #189 which fixes the real cause of the proxy problem.

**Pull request closed without merging**
