### PR TITLE
Support for ios mutable-content

### PR DESCRIPTION
**Pull request by SemonCat**
FCM added the mutable_content field to API

see https://github.com/firebase/quickstart-ios/issues/70 for more detail

### CODE REVIEW

**Comment by eladnava** [comment]
@SemonCat Looks good, however, can you write some tests, please? Check that the parameter is set successfully and sent to the FCM API and setting it to something other than a boolean is invalid.

Thanks!

**Comment by SemonCat** [comment]
HI, @eladnava ,

Sorry, I only add mutable_content to json check,

Is your master branch check arguments type?

I pass string to contentAvailable and it didn't block it.

**Comment by eladnava** [comment]
OK thanks @SemonCat I think that's good. It looks like at this time we don't validate the message parameters' types.

Can we merge @hypesystem?

**Comment by SemonCat** [comment]
Hi, @eladnava ,

Sorry to bother you,

but I really need this option for fcm push.

any thing I can do to speed up merge?

**Comment by eladnava** [comment]
I will go ahead and merge since the tests pass and this looks good to me. Let me know when you get a chance to look at it @hypesystem.

**Comment by eladnava** [comment]
Released 0.14.6 on npm. 👍

**Comment by SemonCat** [comment]
Hi, @eladnava ,

Thanks for your help!👍

**Comment by hypesystem** [comment]
It looks fine to me :-)

**Pull request merged**
