### PR TITLE
adding dependencies installation & test run info in contributing

### PR DESCRIPTION
**Pull request by chirag200666**
I wanted to add a few features, I was struggling to find how to get started with writing code and run the tests, so I created this pull request. Please suggest more things which can help in getting started quickly.

### CODE REVIEW

**Comment by hypesystem** [comment]
This should not be necessary. If you clone and `npm install` the tests should be available with `npm test`. If you had trouble figuring out how to run the tests, though, many other people probably did, too.

So how about a section called **Development**, which tells users how to get started with development? It should probably contain both the clone URL and the correct test command :smile:

**Comment by chirag200666** [comment]
Hi @hypesystem, that would be great and having a link of that in Readme will be helpful.

**Comment by hypesystem** [comment]
If you make the changes, I will merge it :smile:

**Comment by chirag200666** [comment]
@hypesystem can you have a look now.

**Comment by chirag200666** [comment]
Should I move the development to README.md or is it fine in the current CONTRIBUTING.md ?

**Comment by hypesystem** [comment]
I think it is fine in CONTRIBUTING, but you could definitely add a link to the README

**Comment by hypesystem** [comment]
The only comment I have is that for nicer formatting of the code you could use triple-\` followed by `js`. See the [Github Markdown help](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by eladnava** [comment]
@chirag200666 I'd suggest moving the "Development" section you added before the "Become a Collaborator!" section. Also, please be sure to link to it in the [#contents](https://github.com/chirag200666/node-gcm/blob/master/CONTRIBUTING.md#contents).

Good job!

**Comment by hypesystem** [comment]
This looks good to me :)

**Comment by eladnava** [comment]
@chirag200666 Well done!

**Comment by chirag200666** [comment]
thanks @eladnava & @hypesystem :smile:

**Pull request merged**
