### PR TITLE
Add capability to set strictSSL.

### PR DESCRIPTION
**Pull request by marcobrador**
Hello,

I have added a field in the "options" object to set "strictSsl" to false. This comes in handy when behind a corporate firewall with an invalid certificate. :)

Hope you find this useful and gets integrated in the project!

Regards,
Marc

### CODE REVIEW

**Comment by hypesystem** [comment]
Hey! Sorry for the long response time on this, it somehow went missing :) Your code + tests look great!

Could I get you to update the README so the option is shown to outside users?

Also remember to add yourself to the contributors in package.json!

Thank you for your contribution! :smile:

**Comment by marcobrador** [comment]
Hi, thanks for your comments, appreciate it.

Where do you want me to document the usage of such option? In the code snippets of the README I see no example of using the "options" field in the constructor... Maybe we could create a table with all the available options or something like this, just let me know how you prefer it.
Marc

**Comment by hypesystem** [comment]
Hmm... you are right, we currently don't document the options we support. Let's just leave that out. I've created a separate issue for that: #178

Just add yourself as a contributor in package.json and we're golden, good to merge :)

**Comment by marcobrador** [comment]
Done!

**Comment by hypesystem** [comment]
Thank you very much for your contribution! Greatly appreciated!

**Comment by eladnava** [comment]
@marcobrador Note that the parameter `strictSsl` has been renamed to `strictSSL` due to #184.

**Pull request merged**
