### PR TITLE
fixing indentation in a line inside senderSpec

### PR DESCRIPTION
**Pull request by chirag200666**
I got confused when I read the line as it was my first time working with node js tests.

### CODE REVIEW

**Comment by hypesystem** [comment]
Interesting! I have not noticed this before now, but the two lines in the tests saying `if` should be changed to say `it`. Can I get you to do that, too?

**Comment by chirag200666** [comment]
@hypesystem done.

**Comment by hypesystem** [comment]
Thanks :smile:

**Comment by chirag200666** [comment]
@hypesystem the second case which was changed from if to it, which starts from line 125 is failing. Can you have a look at it. Should I create a new issue for the same ?

**Comment by hypesystem** [comment]
That should be a new issue :smile:

**Comment by chirag200666** [comment]
Created, thanks :smile:

**Pull request merged**
