### PR TITLE
Typo in exports

### PR DESCRIPTION
**Pull request by bbqsrc**
`MulitcastResult` -> `MulticastResult`

### CODE REVIEW

**Comment by eladnava** [comment]
Nice catch!

@hypesystem Can we merge?

**Comment by hypesystem** [comment]
This would be a breaking change. We need to also support the wrongly spelled version, in case anyone relies on it.

With v1 we will remove MulticastResult altogether.

@bbqsrc also remember to add yourself to contributors :)

**Comment by eladnava** [comment]
Ah, right. So I guess we should wait for v1 to be completed and merged.

**Comment by hypesystem** [comment]
There are two options, as I see it. I don't have a preference.

1. Do nothing about this for now, as it will go away with v1.
2. Fix it in the master branch, remembering to keep backwards compatibility (ie. supporting *both* names).

**Comment by eladnava** [comment]
I'd say #1 makes more sense.

**Pull request closed without merging**
