### PR TITLE
updated some documentation

### PR DESCRIPTION
**Pull request by jkowalleck**
* added david-db to README
* streamlined some indets in the README
* updated Changelog

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @jkowalleck,
Thanks for the proposed changes.

Can you please explain the logic behind the modifications, specifically:

* .editorconfig - how the addition of this file will improve node-gcm
* .gitattributes - how the addition of this file will improve node-gcm
* whitespace changes - I think the current whitespacing in the README is a more popular way of indentation in JavaScript ([current](https://github.com/ToothlessGear/node-gcm/blob/master/README.md) vs [proposed](https://github.com/jkowalleck/node-gcm/blob/b932c78d93aec19b2b0128f2833059c49df9f9b7/README.md))

Thanks!

**Comment by jkowalleck** [comment]
@eladnava
Will answer your questions later this week.

**Comment by hypesystem** [comment]
@jkowalleck No rush and thank you so much for your time :smile:

**Comment by jkowalleck** [comment]
according to your questions

changes on `.editorconfig` 

* `trim_trailing_whitespace = false` 
  it was added to prevent editors from auto-removing trailing whitespaces. this is used to create linebreaks in blocks. 
  In the `README.md` I used this to put the dependencies badges in the first block one on a new line.   
  according to the docs: https://daringfireball.net/projects/markdown/syntax#p  
  > When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.   
* `indent_style = space` and `indent_size = 3`
   in markdown lists are nested by indenting.  
   but indenting is also needed when a manual linebreak (see above) is done in a list. (some implementations detect manual linebreaks, but its not the standard)

changes on `.gitattributes`

*  i will revert those. i can not remember what my intention was by doing this. proably it was regarding the whitespaces mentioned above.

whitespace changes in README 

* i tried to streamline the indention in the example javascript code. on some points I found tab indents, some used 2spaces, some 4spaces.  
  tab was used more often, so i changed all indents to be tabs.

**Comment by jkowalleck** [comment]
could you close this pull request?
i will split the changes in several PR so you can plug the changes you actually want.

**Comment by hypesystem** [comment]
Sounds good to do it separately, that way the discussion will be less messy, too :smile:

**Pull request closed without merging**
